# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.IntegerField()),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pedido', models.DateField()),
                ('cantidad_requerida', models.IntegerField()),
                ('cantidad_entregada', models.IntegerField()),
                ('cantidad_faltante', models.IntegerField()),
                ('fecha_entrega', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('culpable', models.CharField(max_length=50)),
            ],
        ),
    ]
