# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('culpable', models.CharField(blank=True, max_length=50, null=True)),
                ('ilicito', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='unidad',
            field=models.CharField(default='Metros', max_length=255),
        ),
        migrations.AddField(
            model_name='logventa',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
    ]
