# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20180725_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='Generada', max_length=255),
        ),
    ]
