# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20180726_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='falmacen',
            field=models.CharField(default='Sistemas', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='frecolector',
            field=models.CharField(default='Ventas', max_length=255),
        ),
    ]
