# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20180726_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='culpable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(blank=True, default='Generada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='falmacen',
            field=models.CharField(blank=True, default='Sistemas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='frecolector',
            field=models.CharField(blank=True, default='Ventas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='unidad',
            field=models.CharField(blank=True, default='Metros', max_length=255, null=True),
        ),
    ]
