# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20180801_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='orden_corte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
