# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_orden_corte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logventa',
            old_name='factura',
            new_name='osa',
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='no_part_cli',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='oc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='osa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='paqueteria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
