# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20180801_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad_entregada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad_faltante',
            field=models.IntegerField(default=0),
        ),
    ]
