# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20180801_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='codigo',
        ),
    ]
