# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_venta_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descontaado',
            field=models.BooleanField(default=False),
        ),
    ]
