# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_descontaado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descontaado',
        ),
    ]
