# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_remove_venta_descontaado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_pedido',
            field=models.DateField(),
        ),
    ]
