# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20180802_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descontado',
            field=models.BooleanField(default=False),
        ),
    ]
