# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('medida', models.CharField(blank=True, max_length=50, null=True)),
                ('existencia', models.IntegerField(blank=True, null=True)),
                ('cantidad_caja', models.IntegerField(blank=True, null=True)),
                ('cantidad_rb', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to=productos.models.upload_image_pathb)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('release', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Proveedor'),
        ),
        migrations.AddField(
            model_name='log',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
