# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
