# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='culpable',
            field=models.CharField(blank=True, default='sistemas', max_length=50, null=True),
        ),
    ]
