# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_log_culpable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='culpable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
