# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20180815_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencia_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='existencia_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
