# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20180723_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('culpable', models.CharField(blank=True, max_length=50, null=True)),
                ('ilicito', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, default='Metros', max_length=255, null=True)),
                ('oc', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('no_part_cli', models.CharField(blank=True, max_length=255, null=True)),
                ('paqueteria', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.IntegerField(blank=True, null=True)),
                ('fecha_pedido', models.DateField()),
                ('cantidad_requerida', models.IntegerField()),
                ('cantidad_entregada', models.IntegerField(default=0)),
                ('cantidad_faltante', models.IntegerField(default=0)),
                ('fecha_entrega', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, default='Generada', max_length=255, null=True)),
                ('culpable', models.CharField(blank=True, max_length=50, null=True)),
                ('frecolector', models.CharField(blank=True, default='Ventas', max_length=255, null=True)),
                ('falmacen', models.CharField(blank=True, default='Sistemas', max_length=255, null=True)),
                ('orden_corte', models.CharField(blank=True, max_length=255, null=True)),
                ('descontado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='logventa',
            name='osa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Venta'),
        ),
    ]
