# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20180809_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logventa',
            old_name='osa',
            new_name='producto',
        ),
    ]
