# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_log_ilicito'),
        ('clientes', '0006_auto_20180809_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Cli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_cliente', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('producto_cliente', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
