# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_prod_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_cli',
            name='empresa_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='prod_cli',
            name='producto_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
