# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20180810_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
